-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.catalog_category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    path character varying(255) COLLATE pg_catalog."default" NOT NULL,
    depth integer NOT NULL,
    numchild integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(2048) COLLATE pg_catalog."default",
    is_public boolean NOT NULL,
    slug character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT catalog_category_pkey PRIMARY KEY (id),
    CONSTRAINT catalog_category_path_key UNIQUE (path),
    CONSTRAINT catalog_category_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.catalog_option
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(64) COLLATE pg_catalog."default" NOT NULL,
    type character varying(16) COLLATE pg_catalog."default" NOT NULL,
    required boolean NOT NULL,
    option_group_id bigint,
    CONSTRAINT catalog_option_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.catalog_optiongroup
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT catalog_optiongroup_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.catalog_optiongroupvalue
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    group_id bigint NOT NULL,
    CONSTRAINT catalog_optiongroupvalue_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.catalog_product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL,
    modified_at timestamp with time zone NOT NULL,
    structure character varying(16) COLLATE pg_catalog."default" NOT NULL,
    title character varying(128) COLLATE pg_catalog."default",
    upc character varying(24) COLLATE pg_catalog."default",
    is_public boolean NOT NULL,
    meta_title character varying(128) COLLATE pg_catalog."default",
    meta_description text COLLATE pg_catalog."default",
    slug character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_by_id integer,
    modified_by_id integer,
    parent_id bigint,
    product_class_id bigint,
    CONSTRAINT catalog_product_pkey PRIMARY KEY (id),
    CONSTRAINT catalog_product_slug_key UNIQUE (slug),
    CONSTRAINT catalog_product_upc_key UNIQUE (upc)
);

CREATE TABLE IF NOT EXISTS public.catalog_product_categories
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT catalog_product_categories_pkey PRIMARY KEY (id),
    CONSTRAINT catalog_product_categories_product_id_category_id_9802d7aa_uniq UNIQUE (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS public.catalog_productattribute
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(256) COLLATE pg_catalog."default" NOT NULL,
    type character varying(256) COLLATE pg_catalog."default" NOT NULL,
    required boolean NOT NULL,
    option_group_id bigint,
    product_class_id bigint,
    CONSTRAINT catalog_productattribute_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.catalog_productattributevalue
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    value_text text COLLATE pg_catalog."default",
    value_integer integer,
    value_float double precision,
    attribute_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT catalog_productattributevalue_pkey PRIMARY KEY (id),
    CONSTRAINT catalog_productattribute_product_id_attribute_id_fe6dbc1b_uniq UNIQUE (product_id, attribute_id)
);

CREATE TABLE IF NOT EXISTS public.catalog_productclass
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(256) COLLATE pg_catalog."default" NOT NULL,
    descriptor character varying(2048) COLLATE pg_catalog."default",
    slug character varying(50) COLLATE pg_catalog."default" NOT NULL,
    track_stock boolean NOT NULL,
    require_shop boolean NOT NULL,
    options_id bigint NOT NULL,
    CONSTRAINT catalog_productclass_pkey PRIMARY KEY (id),
    CONSTRAINT catalog_productclass_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.catalog_productimage
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    display_order integer NOT NULL,
    image_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT catalog_productimage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.catalog_productrecommendation
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rank smallint NOT NULL,
    primary_id bigint NOT NULL,
    recommendation_id bigint NOT NULL,
    CONSTRAINT catalog_productrecommendation_pkey PRIMARY KEY (id),
    CONSTRAINT catalog_productrecommend_primary_id_recommendatio_8c19ec22_uniq UNIQUE (primary_id, recommendation_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.inventory_stockrecord
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sku character varying(64) COLLATE pg_catalog."default",
    buy_price bigint,
    sale_price bigint NOT NULL,
    num_stock integer NOT NULL,
    threshold_low_stack integer,
    product_id bigint NOT NULL,
    CONSTRAINT inventory_stockrecord_pkey PRIMARY KEY (id),
    CONSTRAINT inventory_stockrecord_sku_key UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS public.media_image
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(256) COLLATE pg_catalog."default",
    image character varying(100) COLLATE pg_catalog."default" NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    file_hash character varying(40) COLLATE pg_catalog."default" NOT NULL,
    fiel_size integer,
    focal_point_x integer,
    focal_point_y integer,
    focal_point_width integer,
    focal_point_height integer,
    CONSTRAINT media_image_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.catalog_option
    ADD CONSTRAINT catalog_option_option_group_id_deb65ad1_fk_catalog_o FOREIGN KEY (option_group_id)
    REFERENCES public.catalog_optiongroup (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_option_option_group_id_deb65ad1
    ON public.catalog_option(option_group_id);


ALTER TABLE IF EXISTS public.catalog_optiongroupvalue
    ADD CONSTRAINT catalog_optiongroupv_group_id_390ba24d_fk_catalog_o FOREIGN KEY (group_id)
    REFERENCES public.catalog_optiongroup (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_optiongroupvalue_group_id_390ba24d
    ON public.catalog_optiongroupvalue(group_id);


ALTER TABLE IF EXISTS public.catalog_product
    ADD CONSTRAINT catalog_product_created_by_id_4e458b98_fk_auth_user_id FOREIGN KEY (created_by_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_product_created_by_id_4e458b98
    ON public.catalog_product(created_by_id);


ALTER TABLE IF EXISTS public.catalog_product
    ADD CONSTRAINT catalog_product_modified_by_id_0962fa82_fk_auth_user_id FOREIGN KEY (modified_by_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_product_modified_by_id_0962fa82
    ON public.catalog_product(modified_by_id);


ALTER TABLE IF EXISTS public.catalog_product
    ADD CONSTRAINT catalog_product_parent_id_a23e011c_fk_catalog_product_id FOREIGN KEY (parent_id)
    REFERENCES public.catalog_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_product_parent_id_a23e011c
    ON public.catalog_product(parent_id);


ALTER TABLE IF EXISTS public.catalog_product
    ADD CONSTRAINT catalog_product_product_class_id_cacba13f_fk_catalog_p FOREIGN KEY (product_class_id)
    REFERENCES public.catalog_productclass (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_product_product_class_id_cacba13f
    ON public.catalog_product(product_class_id);


ALTER TABLE IF EXISTS public.catalog_product_categories
    ADD CONSTRAINT catalog_product_cate_category_id_f9457ae1_fk_catalog_c FOREIGN KEY (category_id)
    REFERENCES public.catalog_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_product_categories_category_id_f9457ae1
    ON public.catalog_product_categories(category_id);


ALTER TABLE IF EXISTS public.catalog_product_categories
    ADD CONSTRAINT catalog_product_cate_product_id_be67c3f5_fk_catalog_p FOREIGN KEY (product_id)
    REFERENCES public.catalog_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_product_categories_product_id_be67c3f5
    ON public.catalog_product_categories(product_id);


ALTER TABLE IF EXISTS public.catalog_productattribute
    ADD CONSTRAINT catalog_productattri_option_group_id_8e94480b_fk_catalog_o FOREIGN KEY (option_group_id)
    REFERENCES public.catalog_optiongroup (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productattribute_option_group_id_8e94480b
    ON public.catalog_productattribute(option_group_id);


ALTER TABLE IF EXISTS public.catalog_productattribute
    ADD CONSTRAINT catalog_productattri_product_class_id_270834d7_fk_catalog_p FOREIGN KEY (product_class_id)
    REFERENCES public.catalog_productclass (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productattribute_product_class_id_270834d7
    ON public.catalog_productattribute(product_class_id);


ALTER TABLE IF EXISTS public.catalog_productattributevalue
    ADD CONSTRAINT catalog_productattri_attribute_id_41dfc498_fk_catalog_p FOREIGN KEY (attribute_id)
    REFERENCES public.catalog_productattribute (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productattributevalue_attribute_id_41dfc498
    ON public.catalog_productattributevalue(attribute_id);


ALTER TABLE IF EXISTS public.catalog_productattributevalue
    ADD CONSTRAINT catalog_productattri_product_id_a2f52dd5_fk_catalog_p FOREIGN KEY (product_id)
    REFERENCES public.catalog_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productattributevalue_product_id_a2f52dd5
    ON public.catalog_productattributevalue(product_id);


ALTER TABLE IF EXISTS public.catalog_productclass
    ADD CONSTRAINT catalog_productclass_options_id_c10c252a_fk_catalog_o FOREIGN KEY (options_id)
    REFERENCES public.catalog_optiongroup (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productclass_options_id_c10c252a
    ON public.catalog_productclass(options_id);


ALTER TABLE IF EXISTS public.catalog_productimage
    ADD CONSTRAINT catalog_productimage_image_id_56adaf0e_fk_media_image_id FOREIGN KEY (image_id)
    REFERENCES public.media_image (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productimage_image_id_56adaf0e
    ON public.catalog_productimage(image_id);


ALTER TABLE IF EXISTS public.catalog_productimage
    ADD CONSTRAINT catalog_productimage_product_id_1f42dd8c_fk_catalog_product_id FOREIGN KEY (product_id)
    REFERENCES public.catalog_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productimage_product_id_1f42dd8c
    ON public.catalog_productimage(product_id);


ALTER TABLE IF EXISTS public.catalog_productrecommendation
    ADD CONSTRAINT catalog_productrecom_primary_id_9591b88a_fk_catalog_p FOREIGN KEY (primary_id)
    REFERENCES public.catalog_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productrecommendation_primary_id_9591b88a
    ON public.catalog_productrecommendation(primary_id);


ALTER TABLE IF EXISTS public.catalog_productrecommendation
    ADD CONSTRAINT catalog_productrecom_recommendation_id_bf19ddcb_fk_catalog_p FOREIGN KEY (recommendation_id)
    REFERENCES public.catalog_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS catalog_productrecommendation_recommendation_id_bf19ddcb
    ON public.catalog_productrecommendation(recommendation_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.inventory_stockrecord
    ADD CONSTRAINT inventory_stockrecord_product_id_e5d45321_fk_catalog_product_id FOREIGN KEY (product_id)
    REFERENCES public.catalog_product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inventory_stockrecord_product_id_e5d45321
    ON public.inventory_stockrecord(product_id);

END;